### ISSUE TITLE
Gitter room

### ISSUE THREAD

**Issue by TomasMikula** [scalaz/scalaz#1369]
Anyone interested in having a public gitter room for scalaz?

I know there is an IRC channel, but gitter is a lower barrier for people to enter.

Also, I can't even find a mention of the IRC channel it in the README or elsewhere on this site.

**Comment by tonymorris** [comment]
-1 gitter

+1 add the IRC channel to the README

**Comment by vmarquez** [comment]
I think Gitter is good for some things, but I don't believe you can connect
any client to it.  This would be my major concern.

However, as someone who switches computers a lot, locations a lot, etc.
Having history built in to gitter is a big advantage.  We don't have that
for IRC.

--Vincent

**Comment by relrod** [comment]
I'm already on enough chat services. -1 gitter. +1 for throwing the IRC in readme/anywhere else, to make it more accessible.

**Comment by tonymorris** [comment]
History (and playback) can be had by using an IRC bouncer such as ZNC. I
believe this is superior to gitter because I can configure it, even
modify it (FOSS). It just requires me to run a machine such as a freebsd
jail, which is free.

gitter stopped working with the IRC bridge recently; that could be a
client issue though.

I am averse to proprietary chat services, especially where the
advantages are not demonstrated.

**Comment by S11001001** [comment]
Agreed with @tonymorris @relrod; let's stick to IRC and advertise it a little better.

**Comment by aloiscochard** [comment]
@vmarquez do you know about irccloud.com ? Don't want to sound like I'm doing promotion for them, but it's actually a pretty neat way to have a slack/gitter like experience with IRC.

The free version is enough for me, but if you pay it will always remain connected (like a IRC bouncer that Tony was describing).

**Comment by TomasMikula** [comment]
A major benefit of gitter (other than accessibility and built-in history) is the Markdown syntax (including syntax highlighting for Scala code blocks).

I might give irccloud a try.

**Comment by S11001001** [comment]
#1375

**Comment by fommil** [comment]
Gitter is now free software and has a seemless irc server... we could have both. But it would require decomming the freenode channel. As much as I loathe gitter, its history and webaccess does make it super easy to use on the go and I've found a lot of contributors to ensime there.

**Comment by jdegoes** [comment]
With things like Sameroom, it's possible we can have both.

Long-term prospects for Gitter (acquired by Github competitor Gitlab) are perhaps not great, but I do like the out of the box experience (search, etc.) and deep integration w/Github.

**Comment by S11001001** [comment]
@fommil I wouldn't say seamless.

gitterHQ/irc-bridge#52 means you really don't know who's present, and tab-complete on usernames doesn't work. Never mind that you're addressing people `TheWrongWay: `.

gitterHQ/irc-bridge#21 demonstrates the behavior of pasting blocks; it gets superlinearly more annoying the longer the paste is.

```
<odersky> class Foo {
<odersky> [edit]     class Foo {
<odersky> [edit]       def <init>[A](a: A): Foo[A]
<odersky> [edit]   
<odersky> [edit] Should be something like this:    class Foo {
<odersky> [edit]       def <init>[A](a: A): Foo[A]
<odersky> [edit]       type Foo$$A
<odersky> [edit]       private type A = Foo$$A
<odersky> [edit]     }
<odersky> [edit] Should be something like this:    
<odersky> [edit] 
<odersky> [edit]     class Foo {
<odersky> [edit]       def <init>[A](a: A): Foo[A]
<odersky> [edit]       type Foo$$A
<odersky> [edit]       private type A = Foo$$A
<odersky> [edit]     }
```

Exacerbating this, you don't have a moral claim to insist on using paste services, because as an IRC user, you're a second-class member of the room. (This of course is the real underlying problem with using the IRC bridge for migration; it's sort of like how Google made its XMPP/Hangouts bridge deliberately unreliable in order to "encourage" folks to use Hangouts instead of their own clients, but probably much less deliberate than "natural outcome of the motivations at play".)

**Comment by vmarquez** [comment]
FWIW I have been happy with IRCCloud, though it costs money to get an equivalent gitter experience.  I asked if they would consider open source sponsorship in exchange for advertisement but they didn't seem interested.

**Comment by tonymorris** [comment]
FWIW, the gitter bridge to IRC was once annoying and now simply does not work for some IRC clients.

Several on my team use matrix.org, including me.
