### ISSUE TITLE
replace uses of List with IList

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1462]
while going through the typeclass hierarchy I've noticed a lot of uses of `List` where `IList` would be more appropriate.

This is a source and binary breaking change, so needs to go into 7.3.x... but it's also very mechanical and low hanging fruit if somebody wanted to spend a lazy afternoon contributing to scalaz.

**Comment by fommil** [comment]
in fact, looks like sometimes it's possible to replace with `NonEmptyList`, see `ApplicativePlus.many`

**Comment by Jacoby6000** [comment]
I started looking in to this as a chance to make a scalaz contribution, and while going through I noticed that `Nondeterminism` is using `Seq` is a whole bunch of places.  Is there any reasoning behind that?  I don't see anything about it in the doc blocks.

Outside of nondeterminism, Seq seems (appropriately) unused in scalaz.

**Comment by Jacoby6000** [comment]
Building on my question, it looks like the choice of Seq is mainly because of the head/tail methods, and in some cases there doesn't seem to be a good reason at all.

In the cases where there is no reason, should the Seq type be changed?  Also, is there a typeclass with some shape like
```scala
trait Collection[F[_]] extends Empty[F] {
  def head[A](fa: F[A]): Option[A]
  def tail[A](fa: F[A]): Option[F[A]]

  def cons[A](fa: F[A]): Option[(A, Option[F[A]])]
}
```
Could also have a non-empty variant where head is required.


Looks like reducer might be this?

**Comment by TomasMikula** [comment]
@Jacoby6000 Agree your `Collection` would be useful. However, I'm afraid such typeclass would be lawless. (Btw, `Empty` is not a typeclass for the same reason. But we do have a lawless typeclass, `Foldable`.)

Btw, your `cons` is more commonly called `uncons`, and the inner `Option` is unnecessary:

```scala
def uncons[A](fa: F[A]): Option[(A, F[A])]
```

Also note that for pretty much anything other than `List` (e.g. `Vector`, sets, trees), `tail` will have to allocate new objects, so using this interface might not be much more efficient than just using `Foldable#toStream` (where that would be sufficient).

**Comment by Jacoby6000** [comment]
@TomasMikula I was trying to make an interface that would work with OneAnd.. If you remove the Option from the tail, it won't work for those structures. I'm fine with just not supporting those, though.

I wonder if, instead of making a new thing, I just add this to foldable.  There can be a slow default implementation, and then people can override them with faster ones.

I'll look in to the issue some more, toStream might wind up being sufficient.

@jdegoes I totally agree! If there's anything I've managed to hammer in to the heads of the people at work, it's "never use Seq".

**Comment by TomasMikula** [comment]
>  I was trying to make an interface that would work with `OneAnd`.

Oh, in that case the _outer_ `Option` is superfluous, and `head` should return `A` instead of `Option[A]`.

Yeah, you can't implement it on `Foldable`, for the reason you mention, or more generally because all methods on `Foldable` tear down the whole structure&mdash;`F[A]` never appears in the result of any method.

**Comment by Jacoby6000** [comment]
Well... No the outer one is required if you want it to work on non-`OneAnd` structures also. I should've been more clear and said I wanted it to work for both.  If it comes down to it, I'll just ignore the `OneAnd` structures, since they all have non-`OneAnd` counterparts.  Not sure it'll be necessary yet, though.

**Comment by TomasMikula** [comment]
Ah, but if you make it work for both, it will suck for the user. It forces them to handle `Option` when they know the value must be `Some`.

**Comment by Jacoby6000** [comment]
I worked on this a bit, digging in to the `Seq` thing quite a bit more than the `List` thing, and it seems like that should probably be a separate issue.  After building on my `Collection` idea a bit, it seems a lot like a `Reducer`, combined with the ideas from `MonoidK` from cats. The work I did on that is [here](https://github.com/scalaz/scalaz/compare/series/7.3.x...Jacoby6000:%231462-replace-uses-of-list-with-ilist). Most of the changes are in `Nondeterminism` and then the `Task` and `Future` instances. 

Overall, I think having a typeclass (or a set of typeclasses) that allows you to do the things that `Seq` does would be useful. So useful, in fact, that I think I probably am missing something, and all of the requisite things already exist.  I have a suspicion I could've used `Reducer` in all of this, rather than making that weird `Collection` thing. I'll explore that avenue soon, but for now I'll go back to just addressed what this issue is about (using `IList` instead of `List` in places).

**Comment by fommil** [comment]
Did you have a read of the ticket about partition and Unfoldable?

**Comment by Jacoby6000** [comment]
No, I'll go check that out.

**Comment by Jacoby6000** [comment]
Nice to see I was at least mildly on the right track. For now, I'll dedicate my work to eliminating List, I'll follow #1452 and see if I can help there at all.

**Comment by fommil** [comment]
I'm on holiday for a week :-) ping me when I'm back if you want me to take a look, and thanks!
