### ISSUE TITLE
what build tooling do we want for scalaz8?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1464]
There are a lot of really great build tools available nowadays, such as scalafmt, scalafix and a new linter.

I personally prefer to have as much automated as possible, included format on compile, what's the general feeling?

**Comment by jdegoes** [comment]
Automate as much as possible. 👍

**Comment by jvz** [comment]
If possible, scalafix templates to migrate from scalaz7 to scalaz8 would be super useful.

**Comment by ChristopherDavenport** [comment]
You may already be aware but as a tale from the trench, when http4s implemented scalafmt on compile we got hit with an initial round of memory errors, and secondly it was much slower to compile. 

It was eventually frustrating enough to be moved to a different command so that changes could be made normally and then formatted and automated testing happened in our new `sbt ci` command. 

If you were already aware of these concerns, my apologies for repeating them.

**Comment by fommil** [comment]
scalafmt definitely has those problems... sadly. I still think it's worth it. The way it is launched for every project and every configuration is exceptionally inefficient.

**Comment by jdegoes** [comment]
Migration would be very nice. Disappointed to hear about the effect on compilation.

**Comment by fommil** [comment]
An option would be to use the scalafmt CLI in CI and not make it part of the sbt build, which doesn't interfere (but can be a bit irritating sometimes)

**Comment by tonymorris** [comment]
I doubt my opinion is popular, but it is:

1. Scalaz used to be built with a .hs script, many years ago.
2. Nothing better has ever been demonstrated to me.

**Comment by puffnfresh** [comment]
I was going to say the same thing as @tonymorris. The build should be Shake, or similar.

**Comment by fommil** [comment]
I have made my peace with sbt. Although it has many flaws.

**Comment by jvz** [comment]
> Scalaz used to be built with a .hs script, many years ago.

Wait, you can build Scala programs with Haskell scripts? Now this I'd like to see.
