### ISSUE TITLE
[build] swap to sbt-dynscalajs

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1465]
maintaining the build for scalajs and scala-native is a burden for scalaz contributors. compile times are longer, IDE integration is messy, and additional steps must be taken to select the jvm modules. Worst case scenario is that quality could be compromised (or made more awkward, like splitting up source files) on the jvm to workaround js/native.

There is a discussion which discusses the current state of how they want it to be done https://contributors.scala-lang.org/t/alternative-scalajs-scala-native-distribution-mechanisms/1166

I propose that we do not publish by default, because scalajs and scala-native can be distributed separately (or by source) separating out the maintenance burden and pushing it downstream. Perhaps people who are interested in js/native could maintain a separate repo with its own release cycle (maybe use semver plus an extra point)

If anybody wants to write functional programming targeting javascript or native binaries, we should be recommending purescript and haskell, respectively.

**Comment by fommil** [comment]
btw, I'm happy to submit a PR turning everything up to 11 and then wind back?

**Comment by TomasMikula** [comment]
I am that person who "is terrified to look in build.sbt", but cross-building for me has never been an obstacle to contributing. Also, I have only ever contributed platform-independent code.

The situation might be different for `scalaz.effect`, where you might need a lot of platform dependent code. But I would suggest that at least `base` is cross-compiled.

**Comment by jdegoes** [comment]
@fommil I am very sympathetic to this proposal.

Playing devil's advocate, Scalaz 7 has support for Scala.js already. Additionally, cross-platform code could be considered an argument for people to choose one library over another. At work, we want to reuse a parser across Javascript and JVM, for example.

I think it would help to do a poll and see how many people exist at the intersection of (Scala & frontend & FP). If it's zero or close to zero, there's no good reason for having cross-platform done as part of Scalaz. If it's not close to zero, I suppose that would be a discussion.

Also agreed on recommending PureScript and Haskell in cases where people have the option. 👍

**Comment by fommil** [comment]
https://github.com/sjrd/sbt-dynscalajs looks like a better way to cross build for scalajs, newly released today in response to my request to make it easier for the community to support scalajs!

**Comment by puffnfresh** [comment]
> If anybody wants to write functional programming targeting javascript or native binaries, we should be recommending purescript and haskell, respectively.

And if anybody wants to write FP targeting the JVM, they probably shouldn't, or use [Eta](http://eta-lang.org/).

**Comment by TomasMikula** [comment]
> > If anybody wants to write functional programming targeting javascript or native binaries, we should be recommending purescript and haskell, respectively.
> 
> And if anybody wants to write FP targeting the JVM, they probably shouldn't, or use [Eta](http://eta-lang.org/).

I do appreciate when projects are honest about their limitations upfront (unfortunately, that is rarely the case). We could put a note on the front page that Scala is not a great language for FP, and _why._

However, if people want to do FP in Scala anyway, whatever their reason, let's make Scalaz the best option. And it doesn't have to be done with any pretense that Scala or JVM are great.

Back to the cross building issue, again, I don't see cross-building as an obstacle to contributing, at least to `base`. I will defer to @jdegoes for `scalaz.effect` and @xuwei-k for the publishing process. I'm not particularly interested in Scala.js myself. I'm just saying that if the maintenance overhead is negligible, there's no good reason to remove it.

> I think it would help to do a poll and see how many people exist at the intersection of (Scala & frontend & FP).

Wouldn't it be better to estimate the _potential_ there is for Scala frontend FP, rather than current numbers? I wonder if Haskell creators did a poll to estimate how many people were at the intersection of (statically typed & pure FP & lazy) at the time before they went ahead with implementing the language. 😉

**Comment by fommil** [comment]
From what I've seen of https://github.com/sjrd/sbt-dynscalajs it eliminates the burden to contributors. Specifically my issue has always been the multiple project noise and the incompatibilities this causes for ensime. This new plugin allows contributors to pretend scalajs does not exist, and it becomes a maintainer-only problem (and appears to be even easier for maintainers).

**Comment by TomasMikula** [comment]
Addressing the issue at the root 👍

**Comment by jvican** [comment]
Hello. I've just happened to come across this thread, and I'd like to give my opinion as a non-user of scalaz.
  
I think that using https://github.com/sjrd/sbt-dynscalajs is not a wise decision. As the README clearly states, several times, it's a plugin that is not going to be maintained and released by Sébastien and whose implementation is fragile (and essentially a hack) that rely on classloading to get the job done. Unless you really enjoy debugging these issues and digging into Scalajs's linker internal APIs, I would probably stay out of it. Maintaining such a plugin is not fun.
  
If you have problems with the current state of sbt-crossproject, I believe you can engineer your build to remove most of the burden that external contributors face. It is not clear to me that this burden exists, and that is experienced by new contributors to this repository (it seems that @TomasMikula has not experienced such a problem), who are unlikely to touch sbt. However, in my next paragraphs I will *assume* that this premise is right.
  
> compile times are longer, IDE integration is messy, and additional steps must be taken to select the jvm modules.
  
If compile times are longer because you run `compile` in the root project, you should really be running `compile` on the JVM project, which you can make the default by calling it `moduleA` instead of `moduleAJVM`. If you're more concrete about the issue that makes compile times longer, I can probably suggest other things you can do at the sbt level.
  
How's IDE integration messy? Those users that use an IDE (like Intellij) only import the build once, and they forget about it (most of them won't ever modify the build.sbt file, and won't reload it). Those users that **do not** use an IDE, they use sbt directly and hence have no issue here.
  
I don't understand the sentence "additional steps must be taken to select the jvm modules". I guess you mean that your build and CI scripts have to be aware that they cross-compile. If this is the case, it will also happen with sbt-dynscalajs.
  
>  Worst case scenario is that quality could be compromised (or made more awkward, like splitting up source files) on the jvm to workaround js/native.
  
This is not addressed either way. If you use `sbt-dynscalajs` you still have to split up source files to make them cross-compile if their dependencies are Java or JVM related. So if this ever happens, you'll need to do it no modularize your build to cross-compile to JS. Scala Native cross-compiles almost all the same libraries than Scalajs, so adding the same (or reusing the JS sources for native) has almost no overhead.
  
> If anybody wants to write functional programming targeting javascript or native binaries, we should be recommending purescript and haskell, respectively.
  
Sure, that's fair. I just want to point out an obvious issue here: the required investment to maintain different codebases in different languages is **high**, and the ROI is clearly lower than just having one codebase that cross-compiles to three different runtimes. Sure, Scala is not the ideal FP language, you can argue ROI is way higher long-term. But sometimes what it's nice (or better), it's not possible given real-world constraints. And I expect people from companies to use Scalaz in production.
   
> I propose that we do not publish by default, because scalajs and scala-native can be distributed separately (or by source) separating out the maintenance burden and pushing it downstream.
  
It's a valid point that cross-compiling takes more CI time than not cross-compiling.
  
As you seem to care about this, have you considered only cross-compiling for pushes to master *or* tags? The abstractions that scalaz provides to their users are by definition hand-rolled and portable, so it would be really unlikely that a contribution compiles with scalaz and fails to compile with scalajs/scala native. *At worst*, you will only notice that doesn't cross-compile when it hits master (no issue here, contributors don't wait on CI for commits that hit master) or before a release. You can choose which one fits you best in exchange of faster compile times in the CI.
  
In any case, note that if you use `sbt-dynscalajs` you will still take the CI time to cross-compile to scalajs, which is already expensive.
  
Lastly, I'd like to point out that it seems to me that you're more frustrated with sbt than the current cross-compiling infrastructure.
  
I could enumerate you lots of other things that could be improved in the build tool to make it faster/easier to configure and maintain. I think that the impact in readability and maintainability when adding cross-compilation to sbt is almost zero in comparison with the array of bad sbt patterns/habits that library authors use everyday. IMO, those are the ones that really screw up sbt builds' hygiene, and those are the ones that should be weeded out...
  
No matter what you eventually decide, have y'all a nice day.

**Comment by fommil** [comment]
@jvican as an ensime user surely you must have noticed how broken it can be at times when using the sbt-scalajs plugin? One obvious problem is which project should ensime resolve any given source file to? Actually it is random, giving it a 50% chance of finding the one with the `.class` files on any given query, and a 50% chance of using the correct sbt project when issuing build commands. To fix it would be a **lot** of work, across at least the server, sbt plugin, and all the text editors. The problem is worse if sbt-native is enabled, giving a 33% chance of finding the right project. That's not even to mention the problems incurred when the scala-native projects are on a different version of scala than everything else...

As you know, I am no longer maintaining ensime, so there is nobody available to perform these fixes. The only reason it works at all in Scala-IDE and IntelliJ is because of commercially funded effort to workaround the peculiarities of a scalajs build.

In fact I believe it is less work to maintain `sbt-dynscalajs` than to use `sbt-scalajs`... or better yet, use `sbt-dynscalajs` and hope that a scalajs user / contributor steps up to maintain it if having scalaz (or whatever) binaries available is of value to them.

I'm definitely mostly frustrated with the need to cross compile at all, and the multiple projects (which I consider to be horrible sbt hygiene). `sbt-dynscalajs` does a great job of fitting within a more standard sbt workflow.

Breaking `master` is unpalatable to me.

**Comment by jvican** [comment]
> One obvious problem is which project should ensime resolve any given source file to? Actually it is random, giving it a 50% chance of finding the one with the .class files on any given query, and a 50% chance of using the correct sbt project when issuing build commands.
  
I believe https://github.com/ensime/ensime-sbt/issues/359#issuecomment-332345852 can be fixed with a smarter analysis in ensime-sbt, because all the info is there on the settings. We can discuss this in the issue directly instead of here.
  
FTR, I do not think that cross-compilation is a hack. Scalajs and Scala Native plugins are normal sbt plugins that add build steps to link their code and run it. And they use public sbt APIs to do so.
  
> As you know, I am no longer maintaining ensime, so there is nobody available to perform these fixes. The only reason it works at all in Scala-IDE and IntelliJ is because of commercially funded effort to workaround the peculiarities of a scalajs build.
  
To the best of my understanding, there's no special handling of scalajs nor scalanative builds in Intellij. It all comes with sbt. Their presentation compiler only consumes inputs from their inject Intellij sbt plugin.
  
> In fact I believe it is less work to maintain sbt-dynscalajs than to use sbt-scalajs... or better yet, use sbt-dynscalajs and hope that a scalajs user / contributor steps up to maintain it if having scalaz (or whatever) binaries available is of value to them.
  
Having read the plugin sources and having some understanding of what's going on in both sbt and scalajs, I'm not sure it will be *less* work. Also, note that sbt-dynscalajs cannot have some of the features that sbt-scalajs has by design, so Scalajs users that really care about this will likely not be able to use sbt-dynscalajs.
  
> I'm definitely mostly frustrated with the need to cross compile at all, not sbt, and sbt-scalajs' creation of multiple projects (which I consider to be unhygienic). sbt-dynscalajs does a great job of fitting within a more standard sbt workflow... treating scalajs like another version of scala.
  
It's nicer, point taken. But it has clear disadvantages. IMO, it's less than ideal.
  
> You can't say there is no overhead to sbt developers. When type core/compile, I don't expect it to do all the scalajs stuff it does.
  
If you do this is because core should actually be the JVM module, so that people do not run `compile` on the aggregated super project. This is what circe does, and it's really simple to do. I have no idea why this is not the recommended way to do it in the Scalajs and sbt docs.
  
There are definitely other ways to improve this and other problems from the sbt side, and fixing those would require you less time than adopting an unmaintained sbt plugin that already makes you pay for most of the things you'd like to ideally remove.
  
> Breaking master is unpalatable to me.
  
You can also choose to do it with releases, or choose a random approach (run cross-compilations in one of every ten commits).
  
I have no idea about the long-term goal of Scalaz. Some days ago I saw a tweet from @jdegoes that says that the vision is to attract non-fp Scala developers (the majority) [in this tweet](https://twitter.com/jdegoes/status/912431964816236544).
  
Cross-compiling is common in the Scala community, so removing it may hamper adoption. My advise is that if it's such a problem for you, it's best to cross-compile with official maintained plugins and slightly tweak your build to make it nicer to use by external contributors.

**Comment by sjrd** [comment]
Well, I was trying to stay away from commenting on this issue, but the accumulation of technical inaccuracies is irking me too much.

> [sbt-dynscalajs]'s a plugin that is not going to be maintained and released by Sébastien and whose implementation is fragile (and essentially a hack) that relies on classloading to get the job done.

It uses classloading, and I won't maintain it (I will release new versions with contributions), but it is neither fragile nor a hack. It only relies on the public, specified API of the Scala.js linker, which is as much as what sbt-scalajs does too. If classloading is a hack, then sbt in its entirety is a hack. In particular its integration with scalac.

> FTR, I do not think that cross-compilation is a hack. Scalajs and Scala Native plugins are normal sbt plugins that add build steps to link their code and run it. And they use public sbt APIs to do so.

Yup, and likewise, sbt-dynscalajs is not a hack either.

> How's IDE integration messy?

IntelliJ has suboptimal support for crossProject. It is not very happy with the same source file pertaining to two different projects, with their respective classpaths. A lot of effort has been poured into IntelliJ so that it supports crossProject at all, by emulating a shared third project that the other two depend on. This is not optimal, as it means that the shared sources cannot see the symbols declared in platform-specific parts.

Scala IDE happens to superbly handle crossProjects, because it has a completely different underlying model. In Eclipse, an open tab represents a file *in a project*. You can open two tabs for the same file, as long as it is through two different projects. Each tab will display the file as a part of the corresponding project, with its classpath and all. So Scala IDE got lucky for crossProjects.

> > The only reason it works at all in Scala-IDE and IntelliJ is because of commercially funded effort to workaround the peculiarities of a scalajs build.
>
> To the best of my understanding, there's no special handling of scalajs nor scalanative builds in Intellij.

So as I said above, in fact in IntelliJ it works because of the commercially funded effort. For Scala IDE, it got lucky and required no additional support.

> I could enumerate you lots of other things that could be improved in the build tool to make it faster/easier to configure and maintain.

And do you think all those things can be fixed with a proof of concept written in the span of 48 hours? And fitting in about 500 LoCs to boot?

> In fact I believe it is less work to maintain sbt-dynscalajs than to use sbt-scalajs...

I believe this is true, indeed, given your requirements.

> Also, note that sbt-dynscalajs cannot have some of the features that sbt-scalajs has by design, so Scalajs users that really care about this will likely not be able to use sbt-dynscalajs.

That doesn't matter in the slightest because the limitations of sbt-dynscalajs only apply to the build in which it is used, not on users of a library built with it. Downstream Scala.js users of scalaz wouldn't see the difference. In fact there wouldn't *be* a difference once published. An artifact produced by sbt-dynscalajs is indistinguishable from one produced by sbt-scalajs.

> I have no idea why this is not the recommended way to do it in the Scalajs and sbt docs.

We do not officially recommend anything. Personally, I always recommend not to have aggregating projects at all, and possibly reroute some tasks in the top-level project to the JVM part in a crossProject. This is what I did in scala-collection-strawman, for example. Nevertheless, a lot of sbt users seem to love aggregation, and so the existing practices survive despite my advice.

**Comment by japgolly** [comment]
Well, this is a very disappointing thread. Please don't drop Scala.JS support.

> If anybody wants to write functional programming targeting javascript or native binaries, we should be recommending purescript and haskell, respectively.

> Also agreed on recommending PureScript and Haskell in cases where people have the option.

1) There's a huge advantage to being able to share code/data/logic between the back and front ends of a webapp.

2) That same reasoning could be applied to the JVM as well. *"If anyone wants to write functional programming for backends / native binaries they should be using Haskell. If anyone wants to write functional programming for the JVM they should be using Eta."* That implies this entire project should be deleted. If that's anyone's level of enthusiasm and interest to Scala & FP / Scalaz then I don't understand your involvement here.

> I think it would help to do a poll and see how many people exist at the intersection of (Scala & frontend & FP). If it's zero or close to zero, there's no good reason for having cross-platform done as part of Scalaz. If it's not close to zero, I suppose that would be a discussion.

I use Scalaz + Scala.JS very heavily and have been for years. Through [scalajs-react](https://github.com/japgolly/scalajs-react) I've also inspired many others to embrace Scalaz in their webapps too. In fact React-intertwined state monads ([example](https://japgolly.github.io/scalajs-react/#examples/state-monad)) provide a brilliant solution to making certain types of code work naturally despite the fact that the semantics of React itself prevents said styles.

> This new plugin allows contributors to pretend scalajs does not exist, and it becomes a maintainer-only problem (and appears to be even easier for maintainers).

I'll offer my opinion on sbt-dynscalajs as well.

As a maintainer of and contributor to many OSS projects myself, I cannot fathom how this will make anything easier for maintainers. Want to know if Scalaz works? Type `sbt test`. Want to make sure everything compiles while you work on it, np, `sbt ~compile`. If I'm not mistaken this will force all maintainers to continuously have to keep manually switching the targets in sbt to JS, back to JVM, back to JS, back to JVM, forever for the entirety of it's development and maintenance lifetimes.

It will also prevent parallelism. Normally JVM/JS projects compile/test/etc in parallel. If you're constantly switching back and forth between targets you've just made it sequential.

All this, in contrast to a single change to the build, made once, already in place.

The only advantage of using sbt-dynscalajs seems to me to be that it would workaround a  deficiency/bug/whatever in ensime for ensime users. @fommil especially, I understand that appeal given all the time and effort you've put in to doing awesome things with that project, but the cost to maintainers who use sbt directly, and maintainers who don't use ensime, it's huge!

**Comment by fommil** [comment]
@japgolly I advise you read the entire thread because you have misinterpreted what is being discussed.

**Comment by japgolly** [comment]
@fommil I just re-read the entire thread. I still don't understand what I have, and/or what you think I've have, misinterpreted. My response still seems entirely relevant to me. Please help. Could you be more specific?

**Comment by fommil** [comment]
@japgolly

1. we already agreed ages ago not to drop scalajs, so there is no reason to be "disappointed" or to argue for keeping it.
2. The scalajs authors themselves have acknowledged the maintenance tax and this new plugin is a step in the right direction. If you don't think it makes things easier, please report a bug with them. You may be somewhat biased towards scalajs given your projects, it is designed for people who primarily care about the jvm, letting the CI (or a final step) warn about js problems.
3. This has nothing to do with ensime.

**Comment by japgolly** [comment]
1. Is there agreement? I saw arguments in favour of not dropping but I don't recall seeing any agreement or decision either way.

2. I find your first two sentences a bit disingenuous. Raise a bug with them? Come on, you well know sbt-dynscalajs is not the official, nor a supported method. But yeah fair point regarding the rest. Scala.JS is pretty central to me but I couldn't care less about Scala 2.10. Framed that way, I can see how letting it go to CI for non-JVM is good enough if you nearly never care. (That being said though, you're still increasing the time it takes for releases. Every time I do one, it shits me that cross-Scala releases run sequentially but there's nothing to be done about that. `crossVersions` is the real hack in sbt if you ask me.)

3. With this page open, ctrl-f ensime. I didn't introduce it as a topic.

And I just saw that you added this to your comment *"The hint is in the title."*
Don't be a dick.

**Comment by fommil** [comment]
@japgolly yes there is agreement to not drop scalajs in light of this new plugin. If it were not for this new plugin, I'd still advocate to drop scalajs and make the scalajs user community create their own fork / releases.

I think the new plugin could result in faster and clearer PR feedback. The CI can run in parallel, for one.

If you primarily care about JS then you can just go into that mode as soon as you start sbt.

If you raise a bug with Seb I'm absolutely certain he will help you fix anything you discover (he just might not fix it himself). I'm sure we'll find things, it's pretty new. I think the liability of maintaining scalajs crossbuilds of popular libraries should fall with the scalajs user community, not the wider FLOSS community nor the scalajs authors.

The community really needs a scala-native version of this plugin.

I brought up ensime as a solid example of how it complicates build tooling. In fact, scalajs complicates the entire tooling ecosystem, it is not limited to ensime. It's my go-to example for build tooling, as I'm sure you can appreciate. If you want to find out more about tooling, come along to the next scala tooling conference, Scalasphere Jan 2018, and we can all talk more about it.

I am afraid I cannot avoid being "a dick", if that is what you think I am doing by expressing a strong opinion on tooling after several bitter bitter years of being neck deep in it.

**Comment by jdegoes** [comment]
@japgolly Yes, currently we will not drop support for scalajs, and this ticket is merely to transition to sbt-dynscalajs (or its successor).

The goal is to find a way to make the "1% tax" bearable for the 99%, and this plugin looks like a way of going about that. If anything it should make scalajs support more stable and more tenable long-term.

In any case, if the direction of scalajs support wasn't clear at the beginning, it should be clear now, and yeah, we all have strong opinions on this, but that's good and healthy! If you'd like to help out with our scalajs support, I'm sure we'd welcome your assistance.

**Comment by fommil** [comment]
@japgolly it's ok, "don't be a dick" is basically a language primitive where I'm from :wink:
