### ISSUE TITLE
Boilerplate generators for sum types

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1510]
I was mentoring a GSoC this past summer on this project https://gitlab.com/fommil/stalagmite which was an experiment in alternatives for case class for FP style (e.g. stronger memoisation, assumptions of immutability). It spawned off stalactite (scalaz-deriving).

But there are a few other ideas in there we might want to cherry pick for scalaz 8. https://gitlab.com/fommil/stalagmite/issues

One of them is convenient sum types. e.g. imagine if you do

```scala
@sum sealed abstract class Super
case class A(i: Int) extends Super
case class B(s: String) extends Super
```

that the case class constructors could be private and generated methods are put on

```scala
object Super {
  def a(i: Int): Super = ...
  def b(s: String): Super = ...
}
```

possibly even retaining the capitalisation.

what think ye?

**Comment by TomasMikula** [comment]
How would you pattern match on `Super`?

**Comment by fommil** [comment]
The unapply would still be public. As would the type.

**Comment by TomasMikula** [comment]
Ah, OK.

It definitely saves _writing_ some boilerplate. I would rather optimize for _reading_, though. Having methods whose definition is missing in the source code can be confusing for someone casually studying the source code.

**Comment by fommil** [comment]
yeah, it's always the trade off...

**Comment by ritschwumm** [comment]
another interesting point: it's easy to slip a bug into handwritten boilerplate, e.g. swap the order of two case class fields with the same type or something like that. to be sure, i have to read all the boilerplate code - and not just the generator.
i'd prefer the latter, because (as most humans) i'm bad a spotting a single tiny variation in a longish piece of code repeating the same pattern over and over again.

**Comment by TomasMikula** [comment]
So you avoid the danger of mixing up arguments in the boilerplate, which is good, but the danger remains for users of the library. I would try to look for a solution that eliminates the danger for both me (the library author) and the user. For example
 - Could I use type tags to avoid mixing up arguments?
 - Instead of `Monoid` (where arguments to multiplication are easily mixed up), could I use `Category` (where composition is type-aligned)?

**Comment by fommil** [comment]
I guess this is a problem that will re-occur with boilerplate generators in scalaz8... probably the sensible approach is to decide (possibly in the coding standards doc that I've yet to see) what things we're willing to use boilerplate generators for. I've heard of lots of boilerplate generator ideas over the years but surprisingly few of them stick. The only ones I use are simulacrum (`@typeclass`) and stalactite (`@deriving`).

**Comment by Jacoby6000** [comment]
I think its reasonable to generate code for methods which are the same for all sums.  `fold` for example. Simulacrum does this, too afaict.  Anything which doesn't have accompanying source is consistent between all generated things, like `FooTypeclass.apply[A]: FooTypeclass[A]`. Everything else has some sort of source analogue to look at.
