### ISSUE TITLE
ValidationNel and NonEmptyList are invariant

### ISSUE THREAD

**Issue by uryyyyyyy** [scalaz/scalaz#1671]
Thanks for great FP library.

In cats, both are covariant.
https://github.com/typelevel/cats/issues/1419

but in scalaz, both are invariant.
https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/NonEmptyList.scala#L10

Do you have any reason?

**Comment by jbgi** [comment]
Indeed there is. See links https://github.com/scalaz/scalaz/issues/1469#issuecomment-334975979

Basically variance annotations increase chance of scalac inferring the wrong types. It was decided that their added complexity and related scalac bugs is not worth it because the problem that sub-typing is trying to solve can be better solved via other mechanisms (eg. type classes, lenses, leibniz/liskov ...).

**Comment by uryyyyyyy** [comment]
Oh... I see...
I will convert these types to Either or List or else.
Thanks!

**Comment by Jacoby6000** [comment]
@uryyyyyyy I recommend trying to stick with invariant structures.  They will hurt a lot less in the long run... There are just a few scala idiosyncrasies to get used to first.

**Comment by joroKr21** [comment]
I have never seen a proper explanation of the reasoning behind this. The linked discussion is about _how_ to implement invariance but not _why_. Is it just folklore and fear from ancient compiler bugs? I get why type classes should be invariant but invariant data types are soo cumbersome to use in Scala. It's like you're trading bad type inference for no type inference at all, because now you have to specify all type parameters manually.

Anyway, I love Scalaz a lot but this part of it feels like sacrificing a lot of usability.

**Comment by tonymorris** [comment]
Variance does not improve type-inference. It moves. If you more often use the cases where type-inference is beneficial, it will look like variance is a great idea. As you tend toward exploiting FP, this stops being the case and the trade-off with type-inference stops existing. It's a no-factor.
