### ISSUE TITLE
Rename scalaz.Void

### ISSUE THREAD

**Issue by KadekM** [scalaz/scalaz#1819]
#1818 led to @edmundnoble (on gitter) suggesting to consider renaming `scalaz.Void` to something that doesn't clash with `java.lang.Void`.
Any suggestions or different opinions?
label: scalaz8

**Comment by jbgi** [comment]
`Nil` and `Nothing` are already taken, maybe `Nought`?
But not using `Void` would reduce the discoverability of the concept.

**Comment by jdegoes** [comment]
It's true that not using `Void` reduces the discoverability of the concept, because that's what this thing is called in other languages. If only the `std` weren't imported by default... which we can fix in Scalaz 8, of course (and should), but not so easy to fix in user's code.

Other options: `Empty` `Uninhabited` `Initial`

**Comment by ktonga** [comment]
`∅`

**Comment by hepin1989** [comment]
`NotUsed` and `Done`?

**Comment by TomasMikula** [comment]
My preferences, in descending order:

1. Keep `Void`
2. `Uninhabited`
3. `Impossible`

**Comment by NeQuissimus** [comment]
My vote is for keeping `Void`.
We should probably update the build to not import anything.

**Comment by jdegoes** [comment]
Can you write that up in a ticket? Good beginner issue.

We can also bake it into Scalazzi

**Comment by NeQuissimus** [comment]
#1821

**Comment by jdegoes** [comment]
@NeQuissimus 🙏 

Closed in favor of #1821.
