### ISSUE TITLE
Suspicious implicit conversions

### ISSUE THREAD

**Issue by larsrh** [scalaz/scalaz#839]
In https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/syntax/ApplySyntax.scala#L85-L87:

```scala
  implicit def lift2[A,B,C](f: (A,B) => C) = F.lift2(f)
  implicit def lift3[A,B,C,D](f: (A,B,C) => D) = F.lift3(f)
  implicit def lift4[A,B,C,D,E](f: (A,B,C,D) => E) = F.lift4(f)
```

**Comment by edmundnoble** [comment]
This is implicitly lifting functions into Apply; it also explains a type error I've been seeing recently:
```scala
scala> val fun: (Int, Int) => Int = _ * _
fun: (Int, Int) => Int = <function2>

scala> fun(Some(1), Some(2))
<console>:15: error: could not find implicit value for parameter F: scalaz.Apply[Some]
              fun(Some(1), Some(2))
              ^
```
I don't think that this is a good thing to keep; it's confusing because the user can make a mistake with parameter types and get back a completely different function than they wanted. Also, with regards to consistency - if we're doing this, why not implicitly lift functions into ordinary functors as well?
Is there any reason why lift5, lift6, and lift7 aren't implicitly provided by this too?

If there are no objections, I'll make a pull request removing these conversions.

**Comment by S11001001** [comment]
@edmundnoble Yes, we should remove them.

@pchiusano These are from fbb8900cb1b8b64550aafc5a19b76ad24d1f5653; how do you feel about them these days?
