### ISSUE TITLE
`Memo` functions based on `immutableMapMemo` are not actually thread-safe

### ISSUE THREAD

**Issue by utaal** [scalaz/scalaz#929]
The scaladoc describes them as thread safe, however the implementation is not as concurrent requests can overwrite each other's updates to the immutable map.
Minimal test case:

    import scalaz._
    import Scalaz._

    import scala.concurrent.{Future, Await}
    import scala.concurrent.ExecutionContext.Implicits.global
    import scala.concurrent.duration._

    object Main extends App {
      println("start")

      val memoized: Int => Int = Memo.immutableHashMapMemo { x =>
        println(x)
        x
      }

      Await.result(Future.sequence((1 to 1000).map(i => Future { memoized(i) })), 5 seconds)
      println("------")
      Await.result(Future.sequence((1 to 1000).map(i => Future { memoized(i) })), 5 seconds)
    }

Nothing should be printed below the dashes.

**Comment by S11001001** [comment]
It is meant to be thread-safe for functions, that is, pure functions.  We don't mention this because it's a general presumption that functions in scalaz's API are functions, with few exceptions (e.g. IO.apply, unsafeTap).

Making it thread safe for non-functions would be an unnecessary complication for functions.  The acceptance of occasional double calculation for simplified concurrency isn't unique to scalaz (cf. STM transactions, concurrent GHC).

**Comment by varming** [comment]
It is not thread safe for pure functions either. Not all member fields in classes in scala.collection.immutable are vals, i.e. final fields in the byte code (a well-known example is the `tl` var in scala.collection.immutable.List which is updated by the map method https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/List.scala#L288). The assignment to a single variable is insufficient to guarantee that the changes to vars in scala.collection.immutable objects will be visible to a receiving thread. The easiest fix I know of is to make the variable volatile. The updates to vars will then happen before the update to the volatile variable, i.e., before a receiving thread will read from the datastructure.
