### ISSUE TITLE
ircbrowse

### ISSUE THREAD

**Issue by tonymorris** [scalaz/scalaz#973]
Is the ircbrowse feature used by anyone?

I don't use it and I wonder if others might.

**Comment by S11001001** [comment]
I use it to amuse myself with starts sometimes, but that's all.  I'm OK with removing it or replacing it with an "opt in" variant.

**Comment by epost** [comment]
Hi Tony, yes, I use it all the time for learning about the scalaz ecosystem, documenting stuff by linking to it, etc. So much stuff gets discussed on there that would otherwise be completely devoid of context that it's just incredibly valuable, at least to me. I now have a bunch of dead links. :( Is the recorded history still available in some way? If nothing else, I'd like to at least preserve that.

**Comment by tpolecat** [comment]
People ask about logs fairly often. What's the reason for turning it off?

**Comment by tonymorris** [comment]
I suspect it is best to reinstate the logs. They were not removed because of this issue, which I'd have preferred to discuss.

I don't want to bother @chrisdone too much with PRs though. Maybe I can set it up in a FreeBSD jail or some other host. I'm happy to do the work if that is the best outcome. Ideas?

**Comment by coltfred** [comment]
I use it all the time and point people to it frequently. It should be put back up. That's one of the best things about Gitter is that I don't miss messages. Who took it down? Can't we just put it back up where it was? cc/ @chrisdone

**Comment by jedws** [comment]
I'd prefer to see it up, I think ircbrowse is a great place for it – unless
Chris Done objects.

**Comment by chrisdone** [comment]
I removed it because @tonymorris opened a PR to remove it: https://github.com/chrisdone/ircbrowse/pull/11 

Adding it back as per https://github.com/chrisdone/ircbrowse/pull/12…

**Comment by tonymorris** [comment]
It is back after discussion. Thanks everyone for your input. Thanks Chris Done for your help and persistence.
